/*                                                                                           
*  Touch Sensing Library System Setup File                                                   
*                                                                                            
*  Auto-generated by System Setup Creator Tool                                               
*                                                                                            
*  This file contains electrode and other Touch Sensing System setup parameters              
*/                                                                                           

#ifndef __TSS_SYSTEM_SETUP_H__
#define __TSS_SYSTEM_SETUP_H__


/* TSS features settings */

#define TSS_USE_DELTA_LOG                 1

#define TSS_USE_SIGNAL_LOG                1

#define TSS_USE_GPIO_STRENGTH             0

#define TSS_USE_GPIO_SLEW_RATE            0

#define TSS_USE_IIR_FILTER                0

#define TSS_USE_NOISE_AMPLITUDE_FILTER    0

#define TSS_USE_DATA_CORRUPTION_CHECK     1

#define TSS_USE_FREEMASTER_GUI            1

#define TSS_ENABLE_DIAGNOSTIC_MESSAGES    0
                                                   
#define TSS_N_ELECTRODES                  35        /* Number of electrodes present in the system */

/* Electrode's GPIOs configuration */

/* Slider Electrode Group */


#define TSS_E0_P                    B               /* Electrode port */
#define TSS_E0_B                    0               /* Electrode bit  */

#define TSS_E1_P                    B               /* Electrode port */
#define TSS_E1_B                    1               /* Electrode bit  */

#define TSS_E2_P                    B               /* Electrode port */
#define TSS_E2_B                    4               /* Electrode bit  */

#define TSS_E3_P                    B               /* Electrode port */
#define TSS_E3_B                    5               /* Electrode bit  */

#define TSS_E4_P                    B               /* Electrode port */
#define TSS_E4_B                    6               /* Electrode bit  */

#define TSS_E5_P                    B               /* Electrode port */
#define TSS_E5_B                    7               /* Electrode bit  */

#define TSS_E6_P                    B               /* Electrode port */
#define TSS_E6_B                    2               /* Electrode bit  */

#define TSS_E7_P                    B               /* Electrode port */
#define TSS_E7_B                    3               /* Electrode bit  */



/* Rotary Electrode Group */


#define TSS_E8_P                    F               /* Electrode port */
#define TSS_E8_B                    5               /* Electrode bit  */

#define TSS_E9_P                    I               /* Electrode port */
#define TSS_E9_B                    0               /* Electrode bit  */

#define TSS_E10_P                   I               /* Electrode port */
#define TSS_E10_B                   3               /* Electrode bit  */

#define TSS_E11_P                   H               /* Electrode port */
#define TSS_E11_B                   7               /* Electrode bit  */

#define TSS_E12_P                   F               /* Electrode port */
#define TSS_E12_B                   4               /* Electrode bit  */

#define TSS_E13_P                   G               /* Electrode port */
#define TSS_E13_B                   3               /* Electrode bit  */

#define TSS_E14_P                   I               /* Electrode port */
#define TSS_E14_B                   2               /* Electrode bit  */

#define TSS_E15_P                   A               /* Electrode port */
#define TSS_E15_B                   1               /* Electrode bit  */



/* LED Electrode Group */


#define TSS_E16_P                   F               /* Electrode port */
#define TSS_E16_B                   0               /* Electrode bit  */

#define TSS_E17_P                   F               /* Electrode port */
#define TSS_E17_B                   1               /* Electrode bit  */

#define TSS_E18_P                   F               /* Electrode port */
#define TSS_E18_B                   2               /* Electrode bit  */

#define TSS_E19_P                   H               /* Electrode port */
#define TSS_E19_B                   6               /* Electrode bit  */


/* Keyboard Electrode Group */


#define TSS_E20_P                   H               /* Electrode port */
#define TSS_E20_B                   3               /* Electrode bit  */

#define TSS_E21_P                   H               /* Electrode port */
#define TSS_E21_B                   2               /* Electrode bit  */

#define TSS_E22_P                   H               /* Electrode port */
#define TSS_E22_B                   1               /* Electrode bit  */

#define TSS_E23_P                   H               /* Electrode port */
#define TSS_E23_B                   0               /* Electrode bit  */

#define TSS_E24_P                   A               /* Electrode port */
#define TSS_E24_B                   7               /* Electrode bit  */

#define TSS_E25_P                   A               /* Electrode port */
#define TSS_E25_B                   5               /* Electrode bit  */


/* MUX Electrode Group */


#define TSS_E26_P                   G               /* Electrode port */
#define TSS_E26_B                   0               /* Electrode bit  */

#define TSS_E27_P                   G               /* Electrode port */
#define TSS_E27_B                   1               /* Electrode bit  */

#define TSS_E28_P                   G               /* Electrode port */
#define TSS_E28_B                   4               /* Electrode bit  */

#define TSS_E29_P                   G               /* Electrode port */
#define TSS_E29_B                   5               /* Electrode bit  */


/* Sizes Electrode Group */

#define TSS_E30_P                   A               /* Electrode port */  
#define TSS_E30_B                   2               /* Electrode bit  */  

#define TSS_E31_P                   H               /* Electrode port */
#define TSS_E31_B                   4               /* Electrode bit  */

#define TSS_E32_P                   F               /* Electrode port */
#define TSS_E32_B                   3               /* Electrode bit  */

#define TSS_E33_P                   H               /* Electrode port */
#define TSS_E33_B                   5               /* Electrode bit  */

/* Rotary Central Electrode */


#define TSS_E34_P                   I               /* Electrode port */
#define TSS_E34_B                   1               /* Electrode bit  */

/* Electrode's measurement type configuration */

/* Controls configuration */

#define TSS_N_CONTROLS              7

/* Slider Electrode Group Control */

#define TSS_C0_TYPE                 TSS_CT_SLIDER   /* Control type */
#define TSS_C0_ELECTRODES           8               /* Number of electrodes in the control */
#define TSS_C0_STRUCTURE            cSlider0        /* Name of the C&S struct to create */
#define TSS_C0_CALLBACK             TSS1_fCallBack0      /* Identifier of the user's callback */

/* Rotary Electrode Group Control */

#define TSS_C1_TYPE                 TSS_CT_ROTARY   /* Control type */
#define TSS_C1_ELECTRODES           8               /* Number of electrodes in the control */
#define TSS_C1_STRUCTURE            cRotary1        /* Name of the C&S struct to create */
#define TSS_C1_CALLBACK             TSS1_fCallBack1      /* Identifier of the user's callback */

/* LED Electrode Group Control */

#define TSS_C2_TYPE                 TSS_CT_KEYPAD   /* Control type */
#define TSS_C2_ELECTRODES           4               /* Number of electrodes in the control */
#define TSS_C2_STRUCTURE            cKey2           /* Name of the C&S struct to create */
#define TSS_C2_CALLBACK             TSS1_fCallBack2      /* Identifier of the user's callback */

/* LED Electrode Group Control */

#define TSS_C3_TYPE                 TSS_CT_KEYPAD   /* Control type */
#define TSS_C3_ELECTRODES           6               /* Number of electrodes in the control */
#define TSS_C3_STRUCTURE            cKey3           /* Name of the C&S struct to create */
#define TSS_C3_CALLBACK             TSS1_fCallBack3      /* Identifier of the user's callback */


/* MUX Electrode Group Control */

#define TSS_C4_TYPE                 TSS_CT_KEYPAD   /* Control type */
#define TSS_C4_ELECTRODES           4               /* Number of electrodes in the control */
#define TSS_C4_STRUCTURE            cKey4           /* Name of the C&S struct to create */
#define TSS_C4_CALLBACK             TSS1_fCallBack4      /* Identifier of the user's callback */


/* DIMENSION Electrode Group Control */


#define TSS_C5_TYPE                 TSS_CT_KEYPAD   /* Control type */
#define TSS_C5_ELECTRODES           4               /* Number of electrodes in the control */
#define TSS_C5_STRUCTURE            cKey5           /* Name of the C&S struct to create */
#define TSS_C5_CALLBACK             TSS1_fCallBack5      /* Identifier of the user's callback */

/* Rotary Central Electrode Control */

#define TSS_C6_TYPE                 TSS_CT_KEYPAD   /* Control type */
#define TSS_C6_ELECTRODES           1               /* Number of electrodes in the control */
#define TSS_C6_STRUCTURE            cKey6           /* Name of the C&S struct to create */
#define TSS_C6_CALLBACK             TSS1_fCallBack6      /* Identifier of the user's callback */

/* Timer Specific parameter */

#define TSS_HW_TIMER                TPM1            /* Defines the name of main TSS HW Timer */

#define TSS_SENSOR_PRESCALER        2               /* Defines the prescaler for all used Timers */
#define TSS_SENSOR_TIMEOUT          1023            /* Defines the timeout for all used Timers */

#endif /*__TSS_SYSTEM_SETUP_H__*/
