/*                                                                                           
*  Touch Sensing Library System Setup File                                                   
*                                                                                            
*  Auto-generated by System Setup Creator Tool                                               
*                                                                                            
*  This file contains electrode and other Touch Sensing System setup parameters              
*/                                                                                           

#ifndef __TSS_SYSTEM_SETUP_H__
#define __TSS_SYSTEM_SETUP_H__


/* Define TSS features settings */

#define TSS_USE_DELTA_LOG                 1

#define TSS_USE_SIGNAL_LOG                1

#define TSS_USE_GPIO_STRENGTH             0

#define TSS_USE_GPIO_SLEW_RATE            0

#define TSS_USE_IIR_FILTER                0

#define TSS_USE_NOISE_AMPLITUDE_FILTER    0

#define TSS_USE_DATA_CORRUPTION_CHECK     1

#define TSS_USE_FREEMASTER_GUI            1

#define TSS_ENABLE_DIAGNOSTIC_MESSAGES    0

#define TSS_N_ELECTRODES                  1         /* Number of electrodes present in the system */

/* Electrode's GPIOs configuration */


#define TSS_E0_P                    A               /* Electrode port */  
#define TSS_E0_B                    2               /* Electrode bit  */  

/* Controls configuration */

#define TSS_N_CONTROLS              1


#define TSS_C0_TYPE                 TSS_CT_KEYPAD   /* Control type */
#define TSS_C0_ELECTRODES           1               /* Number of electrodes in the control */
#define TSS_C0_STRUCTURE            cKey0           /* Name of the C&S struct to create */
#define TSS_C0_CALLBACK             TSS1_fCallBack0      /* Identifier of the user's callback */


/* Timer Specific parameter */

#define TSS_HW_TIMER                TPM1            /* Defines the TSS Timer */

#define TSS_SENSOR_PRESCALER        2               /* Defines the prescaler for all used Timers */
#define TSS_SENSOR_TIMEOUT          511             /* Defines the timeout for all used Timers */

#endif /*__TSS_SYSTEM_SETUP_H__*/
