/*
*  Touch Sensing Library System Setup File
*
*  Auto-generated by System Setup Creator Tool
*
*  This file contains electrode and other Touch Sensing System setup parameters
*/

#ifndef __TSS_SYSTEM_SETUP_H__
#define __TSS_SYSTEM_SETUP_H__


/* TSS Settings */

#define TSS_USE_DELTA_LOG                 1

#define TSS_USE_SIGNAL_LOG                1

#define TSS_USE_GPIO_STRENGTH             0

#define TSS_USE_GPIO_SLEW_RATE            0

#define TSS_USE_IIR_FILTER                0

#define TSS_USE_NOISE_AMPLITUDE_FILTER    0

#define TSS_USE_DATA_CORRUPTION_CHECK     1

#define TSS_USE_FREEMASTER_GUI            1

#define TSS_ENABLE_DIAGNOSTIC_MESSAGES    0

#define TSS_ONFAULT_CALLBACK              TSS_fOnFault /* Identifier of the user's OnFault callback */

#define TSS_N_ELECTRODES                  8            /* Number of electrodes present in the system */

/* Electrode's GPIOs configuration */

#define TSS_E0_P                    G
#define TSS_E0_B                    0

#define TSS_E1_P                    G
#define TSS_E1_B                    1

#define TSS_E2_P                    E
#define TSS_E2_B                    2

#define TSS_E3_P                    E
#define TSS_E3_B                    3

#define TSS_E4_P                    E
#define TSS_E4_B                    6

#define TSS_E5_P                    E
#define TSS_E5_B                    5

#define TSS_E6_P                    E
#define TSS_E6_B                    7

#define TSS_E7_P                    E
#define TSS_E7_B                    4

/* Electrode's measurement method configuration */

/* Controls configuration */

#define TSS_N_CONTROLS              1

#define TSS_C0_TYPE                 TSS_CT_KEYPAD
#define TSS_C0_INPUTS               {0,1,2,3,4,5,6,7}
#define TSS_C0_STRUCTURE            cKey0
#define TSS_C0_CALLBACK             fCallBack0

/* Timer Specific parameter */

#define TSS_HW_TIMER                TPM3       /* Defines the HW Timer */

#define TSS_SENSOR_PRESCALER        5          /* Defines the prescaler for all used Timers */
#define TSS_SENSOR_TIMEOUT          1023       /* Defines the timeout for all used Timers */

#endif /*__TSS_SYSTEM_SETUP_H__*/
